name: Atom
version: '${version}'
main: org.shotrush.atom.Atom
api-version: '1.21'
folia-supported: true
authors: [ShotRush]
website: https://github.com/ShotRush/atom
depend:
  - ProtocolLib
  - CraftEngine